esphome:
  name: m5stack-dmx-controller
  friendly_name: "M5Stack DMX Controller"
  comment: "32 Channel RGBW DMX 512 LED Controller"
  includes:
    - dmx_globals.h
  on_boot:
    priority: -100
    then:
      - light.turn_on: lcd_backlight

esp32:
  board: m5stack-core-esp32
  framework:
    type: arduino

psram:

# Enable logging
logger:
  level: DEBUG

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption_key

ota:
  password: !secret ota_password
  platform: esphome
  
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "M5Stack-DMX-Controller"
    password: !secret fallback_password

captive_portal:

# DMX UART configuration for M5Stack DMX Base
uart:
  - id: dmx_uart
    tx_pin: 13  # M5Stack BASIC/GRAY/GO/FIRE
    rx_pin: 35  # M5Stack BASIC/GRAY/GO/FIRE (not used for DMX output)
    baud_rate: 250000
    data_bits: 8
    stop_bits: 2
    parity: NONE

# Global variables to store DMX channel values and current group
globals:
  - id: dmx_channels
    type: std::array<uint8_t, 513>
    restore_value: no
    initial_value: '{0}'
  - id: current_group
    type: int
    initial_value: '1'

# Scripts for DMX control and button actions
script:
  - id: send_dmx_data
    then:
      - lambda: |-
          // Send DMX break (88μs low)
          digitalWrite(13, LOW);
          delayMicroseconds(88);
          
          // Send mark after break (8μs high)
          digitalWrite(13, HIGH);
          delayMicroseconds(8);
          
          // Send start code and data
          id(dmx_uart).write_byte(0x00); // Start code
          for (int i = 1; i <= 32; i++) {
            id(dmx_uart).write_byte(id(dmx_channels)[i]);
          }

  - id: update_dmx_channel
    parameters:
      channel: int
      value: int
    then:
      - lambda: |-
          if (channel >= 1 && channel <= 32) {
            id(dmx_channels)[channel] = value;
          }
      - script.execute: send_dmx_data

  - id: cycle_groups
    then:
      - lambda: |-
          id(current_group) = (id(current_group) % 8) + 1;
      - if:
          condition:
            lambda: 'return id(current_group) == 1;'
          then:
            - light.toggle: group_1
      - if:
          condition:
            lambda: 'return id(current_group) == 2;'
          then:
            - light.toggle: group_2
      - if:
          condition:
            lambda: 'return id(current_group) == 3;'
          then:
            - light.toggle: group_3
      - if:
          condition:
            lambda: 'return id(current_group) == 4;'
          then:
            - light.toggle: group_4
      - if:
          condition:
            lambda: 'return id(current_group) == 5;'
          then:
            - light.toggle: group_5
      - if:
          condition:
            lambda: 'return id(current_group) == 6;'
          then:
            - light.toggle: group_6
      - if:
          condition:
            lambda: 'return id(current_group) == 7;'
          then:
            - light.toggle: group_7
      - if:
          condition:
            lambda: 'return id(current_group) == 8;'
          then:
            - light.toggle: group_8

  - id: all_lights_off
    then:
      - light.turn_off: group_1
      - light.turn_off: group_2
      - light.turn_off: group_3
      - light.turn_off: group_4
      - light.turn_off: group_5
      - light.turn_off: group_6
      - light.turn_off: group_7
      - light.turn_off: group_8

# Interval to continuously send DMX data
interval:
  - interval: 25ms  # ~40Hz refresh rate
    then:
      - script.execute: send_dmx_data

# I2C for M5Stack internal components
i2c:
  sda: 21
  scl: 22
  scan: true

# SPI bus for internal LCD
spi:
  clk_pin: 18
  mosi_pin: 23
  miso_pin: 19

# M5Stack LCD Display
display:
  - platform: ili9xxx
    model: M5STACK
    id: m5stack_display
    cs_pin: 14
    dc_pin: 27
    reset_pin: 33
    invert_colors: false
    color_palette: 8BIT
    rotation: 270
    update_interval: 1s
    lambda: |-
      it.fill(Color::BLACK);
      it.print(0, 0, id(font_medium), Color::WHITE, "DMX Controller");
      it.printf(0, 25, id(font_small), Color(0, 255, 0), "WiFi: %s", id(wifi_connected).state ? "Connected" : "Disconnected");
      it.printf(0, 40, id(font_small), Color(0, 255, 255), "IP: %s", id(wifi_ip).state.c_str());

      // Show DMX channel values for first 8 channels
      it.printf(0, 65, id(font_small), Color::WHITE, "Ch 1-4: %d %d %d %d",
        id(dmx_channels)[1], id(dmx_channels)[2], id(dmx_channels)[3], id(dmx_channels)[4]);

      it.printf(0, 80, id(font_small), Color::WHITE, "Ch 5-8: %d %d %d %d",
        id(dmx_channels)[5], id(dmx_channels)[6], id(dmx_channels)[7], id(dmx_channels)[8]);

      it.printf(0, 95, id(font_small), Color(255, 255, 0), "Current Group: %d", id(current_group));

# Fonts for display
font:
  - file: "gfonts://Roboto"
    id: font_small
    size: 12
  - file: "gfonts://Roboto"
    id: font_medium
    size: 16

# Text sensors for display
text_sensor:
  - platform: wifi_info
    ip_address:
      name: "IP Address"
      id: wifi_ip
      internal: true

# Binary sensors
binary_sensor:
  - platform: status
    name: "Status"
    id: device_status
  
  - platform: template
    name: "WiFi Connected"
    id: wifi_connected
    lambda: |-
      return WiFi.isConnected();
    entity_category: diagnostic
    icon: "mdi:wifi"

  # M5Stack buttons
  - platform: gpio
    pin:
      number: 39
      inverted: true
    name: "Button A"
    id: button_a
    on_press:
      then:
        - light.toggle: group_1

  - platform: gpio
    pin:
      number: 38
      inverted: true
    name: "Button B"
    id: button_b
    on_press:
      then:
        - script.execute: cycle_groups

  - platform: gpio
    pin:
      number: 37
      inverted: true
    name: "Button C"
    id: button_c
    on_press:
      then:
        - script.execute: all_lights_off

# Output components for DMX channels
output:
  - platform: gpio
    id: lcd_backlight_output
    pin: 32
    inverted: false

  # Output components for DMX channels
  # Group 1 outputs (DMX channels 1-4)
  - platform: template
    id: dmx_ch1
    type: float
    write_action:
      - script.execute:
          id: update_dmx_channel
          channel: 1
          value: !lambda 'return (int)(state * 255);'
  
  - platform: template
    id: dmx_ch2
    type: float
    write_action:
      - script.execute:
          id: update_dmx_channel
          channel: 2
          value: !lambda 'return (int)(state * 255);'
  
  - platform: template
    id: dmx_ch3
    type: float
    write_action:
      - script.execute:
          id: update_dmx_channel
          channel: 3
          value: !lambda 'return (int)(state * 255);'
  
  - platform: template
    id: dmx_ch4
    type: float
    write_action:
      - script.execute:
          id: update_dmx_channel
          channel: 4
          value: !lambda 'return (int)(state * 255);'

  # Group 2 outputs (DMX channels 5-8)
  - platform: template
    id: dmx_ch5
    type: float
    write_action:
      - script.execute:
          id: update_dmx_channel
          channel: 5
          value: !lambda 'return (int)(state * 255);'
  
  - platform: template
    id: dmx_ch6
    type: float
    write_action:
      - script.execute:
          id: update_dmx_channel
          channel: 6
          value: !lambda 'return (int)(state * 255);'
  
  - platform: template
    id: dmx_ch7
    type: float
    write_action:
      - script.execute:
          id: update_dmx_channel
          channel: 7
          value: !lambda 'return (int)(state * 255);'
  
  - platform: template
    id: dmx_ch8
    type: float
    write_action:
      - script.execute:
          id: update_dmx_channel
          channel: 8
          value: !lambda 'return (int)(state * 255);'

  # Group 3 outputs (DMX channels 9-12)
  - platform: template
    id: dmx_ch9
    type: float
    write_action:
      - script.execute:
          id: update_dmx_channel
          channel: 9
          value: !lambda 'return (int)(state * 255);'
  
  - platform: template
    id: dmx_ch10
    type: float
    write_action:
      - script.execute:
          id: update_dmx_channel
          channel: 10
          value: !lambda 'return (int)(state * 255);'
  
  - platform: template
    id: dmx_ch11
    type: float
    write_action:
      - script.execute:
          id: update_dmx_channel
          channel: 11
          value: !lambda 'return (int)(state * 255);'
  
  - platform: template
    id: dmx_ch12
    type: float
    write_action:
      - script.execute:
          id: update_dmx_channel
          channel: 12
          value: !lambda 'return (int)(state * 255);'

  # Group 4 outputs (DMX channels 13-16)
  - platform: template
    id: dmx_ch13
    type: float
    write_action:
      - script.execute:
          id: update_dmx_channel
          channel: 13
          value: !lambda 'return (int)(state * 255);'
  
  - platform: template
    id: dmx_ch14
    type: float
    write_action:
      - script.execute:
          id: update_dmx_channel
          channel: 14
          value: !lambda 'return (int)(state * 255);'
  
  - platform: template
    id: dmx_ch15
    type: float
    write_action:
      - script.execute:
          id: update_dmx_channel
          channel: 15
          value: !lambda 'return (int)(state * 255);'
  
  - platform: template
    id: dmx_ch16
    type: float
    write_action:
      - script.execute:
          id: update_dmx_channel
          channel: 16
          value: !lambda 'return (int)(state * 255);'

  # Group 5 outputs (DMX channels 17-20)
  - platform: template
    id: dmx_ch17
    type: float
    write_action:
      - script.execute:
          id: update_dmx_channel
          channel: 17
          value: !lambda 'return (int)(state * 255);'
  
  - platform: template
    id: dmx_ch18
    type: float
    write_action:
      - script.execute:
          id: update_dmx_channel
          channel: 18
          value: !lambda 'return (int)(state * 255);'
  
  - platform: template
    id: dmx_ch19
    type: float
    write_action:
      - script.execute:
          id: update_dmx_channel
          channel: 19
          value: !lambda 'return (int)(state * 255);'
  
  - platform: template
    id: dmx_ch20
    type: float
    write_action:
      - script.execute:
          id: update_dmx_channel
          channel: 20
          value: !lambda 'return (int)(state * 255);'

  # Group 6 outputs (DMX channels 21-24)
  - platform: template
    id: dmx_ch21
    type: float
    write_action:
      - script.execute:
          id: update_dmx_channel
          channel: 21
          value: !lambda 'return (int)(state * 255);'
  
  - platform: template
    id: dmx_ch22
    type: float
    write_action:
      - script.execute:
          id: update_dmx_channel
          channel: 22
          value: !lambda 'return (int)(state * 255);'
  
  - platform: template
    id: dmx_ch23
    type: float
    write_action:
      - script.execute:
          id: update_dmx_channel
          channel: 23
          value: !lambda 'return (int)(state * 255);'
  
  - platform: template
    id: dmx_ch24
    type: float
    write_action:
      - script.execute:
          id: update_dmx_channel
          channel: 24
          value: !lambda 'return (int)(state * 255);'

  # Group 7 outputs (DMX channels 25-28)
  - platform: template
    id: dmx_ch25
    type: float
    write_action:
      - script.execute:
          id: update_dmx_channel
          channel: 25
          value: !lambda 'return (int)(state * 255);'
  
  - platform: template
    id: dmx_ch26
    type: float
    write_action:
      - script.execute:
          id: update_dmx_channel
          channel: 26
          value: !lambda 'return (int)(state * 255);'
  
  - platform: template
    id: dmx_ch27
    type: float
    write_action:
      - script.execute:
          id: update_dmx_channel
          channel: 27
          value: !lambda 'return (int)(state * 255);'
  
  - platform: template
    id: dmx_ch28
    type: float
    write_action:
      - script.execute:
          id: update_dmx_channel
          channel: 28
          value: !lambda 'return (int)(state * 255);'

  # Group 8 outputs (DMX channels 29-32)
  - platform: template
    id: dmx_ch29
    type: float
    write_action:
      - script.execute:
          id: update_dmx_channel
          channel: 29
          value: !lambda 'return (int)(state * 255);'
  
  - platform: template
    id: dmx_ch30
    type: float
    write_action:
      - script.execute:
          id: update_dmx_channel
          channel: 30
          value: !lambda 'return (int)(state * 255);'
  
  - platform: template
    id: dmx_ch31
    type: float
    write_action:
      - script.execute:
          id: update_dmx_channel
          channel: 31
          value: !lambda 'return (int)(state * 255);'
  
  - platform: template
    id: dmx_ch32
    type: float
    write_action:
      - script.execute:
          id: update_dmx_channel
          channel: 32
          value: !lambda 'return (int)(state * 255);'

# RGBW Light entities (8 groups of 4 channels each)
light:
  - platform: binary
    name: "LCD Backlight"
    id: lcd_backlight
    output: lcd_backlight_output
    internal: true
    restore_mode: ALWAYS_ON

  # Group 1: Channels 1-4 (DMX addresses 1-4)
  - platform: rgbw
    name: "DMX Group 1"
    id: group_1
    red: dmx_ch1
    green: dmx_ch2
    blue: dmx_ch3
    white: dmx_ch4
    effects:
      - random:
      - strobe:
      - flicker:

  # Group 2: Channels 5-8 (DMX addresses 5-8)
  - platform: rgbw
    name: "DMX Group 2"
    id: group_2
    red: dmx_ch5
    green: dmx_ch6
    blue: dmx_ch7
    white: dmx_ch8
    effects:
      - random:
      - strobe:
      - flicker:

  # Group 3: Channels 9-12 (DMX addresses 9-12)
  - platform: rgbw
    name: "DMX Group 3"
    id: group_3
    red: dmx_ch9
    green: dmx_ch10
    blue: dmx_ch11
    white: dmx_ch12
    effects:
      - random:
      - strobe:
      - flicker:

  # Group 4: Channels 13-16 (DMX addresses 13-16)
  - platform: rgbw
    name: "DMX Group 4"
    id: group_4
    red: dmx_ch13
    green: dmx_ch14
    blue: dmx_ch15
    white: dmx_ch16
    effects:
      - random:
      - strobe:
      - flicker:

  # Group 5: Channels 17-20 (DMX addresses 17-20)
  - platform: rgbw
    name: "DMX Group 5"
    id: group_5
    red: dmx_ch17
    green: dmx_ch18
    blue: dmx_ch19
    white: dmx_ch20
    effects:
      - random:
      - strobe:
      - flicker:

  # Group 6: Channels 21-24 (DMX addresses 21-24)
  - platform: rgbw
    name: "DMX Group 6"
    id: group_6
    red: dmx_ch21
    green: dmx_ch22
    blue: dmx_ch23
    white: dmx_ch24
    effects:
      - random:
      - strobe:
      - flicker:

  # Group 7: Channels 25-28 (DMX addresses 25-28)
  - platform: rgbw
    name: "DMX Group 7"
    id: group_7
    red: dmx_ch25
    green: dmx_ch26
    blue: dmx_ch27
    white: dmx_ch28
    effects:
      - random:
      - strobe:
      - flicker:

  # Group 8: Channels 29-32 (DMX addresses 29-32)
  - platform: rgbw
    name: "DMX Group 8"
    id: group_8
    red: dmx_ch29
    green: dmx_ch30
    blue: dmx_ch31
    white: dmx_ch32
    effects:
      - random:
      - strobe:
      - flicker: